version: "3.7"
# define all services
services:
  mysql:
    image: "mysql:drupal"
    restart: "no"
    container_name: mysql_drupal
    ports:
      - "3306:3306"
      - "33060:33060"
    privileged: "true"
    build:
      context: ./
      dockerfile: dockfile/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=Ab@123456
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=Ab123456@
    networks:
      drunet:
        ipv4_address: 172.21.128.2

  httpd:
    image: "httpd:drupal"
    restart: "no"
    container_name: httpd_drupal
    ports:
      - "8080:80"
    privileged: "true"
    build:
      context: ./
      dockerfile: dockfile/httpd
    volumes:
      - "./data/source:/var/www/html"
    networks:
      drunet:
        ipv4_address: 172.21.128.3
  ftpd_server:
    image: stilliard/pure-ftpd
    container_name: ftpd_server
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
      - "./data/source/drupal:/home/username/"
      - "./data/passwd:/etc/pure-ftpd/passwd"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: ssv
      FTP_USER_PASS: ssv@20150601
      FTP_USER_HOME: /home/username
    networks:
      drunet:
        ipv4_address: 172.21.128.4
    restart: always
networks:
  drunet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16