<?php 
/* Hook of mymodule */
function mymodule_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    if($form_id == 'comment_comment_form'){
        $form['actions']['submit']['#value'] = t('Comment');
    }
  }
/* Thực hiện các thay đổi trước khi biểu mẫu được hiển thị.
Thứ tự lệnh gọi như sau: tất cả các hàm thay đổi biểu mẫu hiện có được gọi cho mô-đun A, sau đó là tất cả cho mô-đun B,
 v.v., tiếp theo là tất cả cho bất kỳ (các) chủ đề cơ sở nào và cuối cùng là cho chính chủ đề. 
 Thứ tự mô-đun được xác định theo trọng lượng hệ thống, sau đó theo tên mô-đun.
Trong mỗi mô-đun, các móc thay đổi biểu mẫu được gọi theo thứ tự sau: đầu tiên, hook_form_alter (); 
thứ hai, hook_form_BASE_FORM_ID_alter (); thứ ba, hook_form_FORM_ID_alter ().
 Vì vậy, đối với mỗi mô-đun, các hook chung chung hơn được gọi đầu tiên sau đó là các hook cụ thể hơn. */