<?php

/**
 * Implements hook_theme().
 */
function seminar_theme($existing, $type, $theme, $path) {
  $path = 'modules/custom/seminar/templates';
    return [
      'my_template' => [
        'variables' => ['test_var' => NULL],
        'path' => $path,
      ],
      'seminar_registration_form' => [
        'variables' => [
            'form' => NULL,
            'items' => [],
        ],
        'path' => $path,
        'template' => 'seminar_registration_form',
        'render element' => 'form'
    ],
    ];
  }